SET client_encoding = 'UTF8';

INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Priscila Botella Batalla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Encarnación Alicia Pont Amorós', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gertrudis Reina', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Serafina Gargallo Urrutia', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alejandro Bayona Fabra', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Edelmira del Grau', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Azeneth Lillo Ledesma', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Anastasia Viana Pintor', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Augusto Codina Manzanares', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Victoria Fernández Fuentes', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cintia Chelo Lastra Roselló', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pili de Jaume', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Manuela Rosalva Chacón Torrecilla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Angelita Terrón Ramirez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ale Saez Girona', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luz Soledad Guillen Ramirez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jonatan de Viana', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Odalys Plana', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lucila Torrijos Blanch', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vanesa Hoz Carrasco', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Belen Martí Carbó', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manu de Muñoz', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Zacarías Bautista Vicens', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luciana Solana Maldonado', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felisa Garcés Aller', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Florinda Villalobos', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eva Roman-Sastre', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heliodoro Tomás-Bernad', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pascuala del Fernandez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmelo Pavón Torrecilla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Raquel Sanz Iriarte', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ismael Mosquera Ortiz', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gastón de Cañas', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Inmaculada Duarte Fernandez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eufemia Jover-Olivares', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ulises Plaza Abellán', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rubén Busquets Arribas', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Josué de Sevilla', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('África Pablo Royo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eugenia Gras Bauzà', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Abel Frutos Nieto', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bernardita Cuevas Casal', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Olimpia Vazquez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guadalupe Ramos Poza', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emperatriz Pinto-Campoy', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felicidad del Castellanos', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Glauco Victoriano Rivas Zabaleta', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dorita Neira Alegria', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manolo Javi Ricart Guitart', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Reinaldo Hoyos Puig', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lorenzo Ávila-Taboada', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eliseo Mendoza', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('José del Gutierrez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Encarna Esperanza Téllez Marti', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felicidad Casals Abascal', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosenda Busquets Bueno', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Martirio Tovar Arellano', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adoración Perales Buendía', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clemente Flavio Sierra Puig', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gervasio Casanovas-Tejera', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Renato Martin Folch Girón', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Claudio Navarrete Jove', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jordi del Ruiz', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Miguel Checa Benet', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dolores Figueras-Olmo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Hernán Bolaños Vallejo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cruz Isern Cánovas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Asdrubal Guerrero Luís', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lisandro Cabrera Recio', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rocío Eufemia Calvet Batalla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vinicio Daza Almazán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Constanza Catalina Romeu Roca', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Isa Torrens Blanch', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodoro Carmona Sanjuan', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jeremías Samuel Morcillo Gutiérrez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jordán Aguiló Rueda', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Danilo Aller Valderrama', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felicia Vargas Segura', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dan Arnau-Muñoz', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ismael Miró Cerdán', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jenny Berrocal Casas', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teófilo Romeu Lorenzo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eulalia del Armengol', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rodolfo Pepe Llobet Aguiló', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nico Clemente-Madrid', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leonor Emperatriz Alcalde Uriarte', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bautista Avilés Ibarra', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Goyo Ferrández', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ernesto Villalba', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mario Ramirez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Víctor Blanca Carreras', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marisa Gárate Miguel', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Santiago Segura Uría', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amparo Arranz Falcó', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amalia de Palomino', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pastor Galvez Lillo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carlito Pacheco Carranza', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Toni Alba Bermúdez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Isaías Tejedor-Mir', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marino Villalba Galán', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bernardino Marco Cisneros', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('América Celestina García Durán', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eustaquio Gilabert-Aramburu', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Néstor Pina', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Araceli Rojas Canals', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Melisa de Pellicer', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Benjamín de Solana', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Irene del Llabrés', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Tadeo Muñoz Ramis', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Galo Olivera', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Claudia Sastre Peinado', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cecilia Coello Prieto', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fabio Alcalá', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Josefina de Nogués', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Martín Cruz Fabregat Gomila', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maximino Alemany-Berenguer', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fabricio Puga Cabrera', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Salomé Arteaga Duque', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Martin Lupe Estévez Jaume', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Florentina del Anguita', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Milagros Moya-Bustamante', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leticia Portero Porras', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Chita Aguirre Valbuena', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Débora Marí Zurita', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Benita Gabriela Vilar Becerra', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nicodemo Perelló Sureda', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jafet Domingo Coca', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pastora Nebot Amador', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Roque Benavente', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Constanza Ripoll-Company', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mohamed Páez Cánovas', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luciana Angelina Prat Barragán', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cesar Verdejo Tomás', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maite del Carpio', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Albano Figueras Oliva', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ricardo Zamorano Sancho', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Estrella Montenegro', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fabiana Llabrés Pedro', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clara del Antúnez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Arcelia Ferrándiz Castrillo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valeria del Mata', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Macaria Díaz Arce', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pepe Sancho Navarro Bernat', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bernarda Romero Vara', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Anastasio Vigil', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eloy Pou Gallardo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fernando Casanovas Aguiló', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmelo Alcántara Castell', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Esteban Exposito Gascón', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pili Almudena Escobar Morera', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Loida Villanueva Egea', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ester Villanueva-Marco', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nayara Saura Carpio', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rogelio Criado-Pedro', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dimas Alfredo Sanchez Porta', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fabio Fabra Velasco', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Delfina Felicia Guillen Esparza', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carlota Blanco Bárcena', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Anastasia de Pujol', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fernanda de Bilbao', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pascuala Mármol', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Imelda Martina Pons Grande', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teobaldo Berenguer Andreu', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mónica Fabiola Carrillo Luís', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Camilo Fajardo Gisbert', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ramona Carpio Fonseca', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luis de Gelabert', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Norberto Dueñas', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Desiderio Cruz Solsona', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosa María del Seguí', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ruy Esparza Diez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Moisés Marti-Mateu', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cipriano Alemán Barco', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Máxima Castañeda Casals', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Celestina Blanes Leal', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rita del Bellido', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Josefa Marti-Antón', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Albina Lopez Girón', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yago Gámez Cortes', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Azucena Benítez Pinto', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dorita del Rozas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Primitiva Durán-Granados', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Atilio Moliner Diéguez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrea Tejera Cortina', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Timoteo Badía Zaragoza', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carolina Bermudez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Celso Murillo Llanos', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ernesto de Ávila', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ileana Araceli Hierro Egea', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Estela Marco', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guiomar Rosario Galindo Maldonado', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('José Cayetana Ibarra Vera', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Jesús del Barceló', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alicia Almagro Tejada', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mireia Pérez Giménez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Flora Bibiana Ricart Mate', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Glauco Cueto Benavent', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Del Carmen Zabala Grau', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amalia Camacho Gibert', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Candelas García Canet', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Odalys Gómez Expósito', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gonzalo Vargas Ballesteros', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Severino Báez Sosa', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maricruz Sobrino-Aller', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valerio Suárez-Verdejo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gabriel Riera', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Arsenio Villena Blanch', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Loreto Viña Gordillo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gala Soriano Vilalta', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emma Miriam Elorza Castell', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ramón Company Cuesta', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Margarita Pozuelo Rocha', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Inocencio Batlle Muro', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juana del Villena', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Calixto Adán Torrecilla', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ovidio Moliner Figueras', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ámbar del Ferrando', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cristóbal Castañeda-Abril', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Iris Mosquera Vilar', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Samu Almazán', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emiliano Campos-Mas', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juan Bautista Portillo Bernat', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Casemiro del Vizcaíno', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Renata Romeu Montenegro', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Esteban Gilberto Céspedes Anaya', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Haroldo Sans Giralt', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Azeneth Comas-Pavón', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cruz Quirós-Hierro', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Iker Barceló Noguera', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yésica Barriga', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eliseo Acedo Aguirre', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Claudia Baquero Perelló', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosenda del Cabo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sergio Gras Coello', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Victoria Gaya Alfonso', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Débora Angelita Cervantes Lumbreras', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alejandro Berenguer Pintor', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gregorio Sales', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dorotea Gargallo Barroso', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lupe Jaume-Cabrera', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Claudia Piña Mur', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ibán Verdugo Varela', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amando Agullo Grau', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adán Mendizábal', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ibán de Mateos', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Socorro Prat Palomares', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrés Felipe Ledesma Lumbreras', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Morena Cuevas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emperatriz Lamas Alonso', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Reina Escrivá Murillo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Itziar Rosselló Espada', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ángeles Olivera Marquez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marcela Tomas-Duran', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ricardo Adán Suárez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dafne del Suarez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Benigna Ramos Bas', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fernanda del Villena', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ibán Moya Ibarra', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ale Cabanillas Peinado', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Federico Quintero Calvo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maximiliano Bou Rius', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ibán Pinto Esteban', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eufemia Rivas Collado', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ligia Quevedo Font', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Federico Acero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Hortensia Posada Viana', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jaime Moreno Larrañaga', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Norberto Guardia Egea', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jordi Durán Fuente', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sara Corral Céspedes', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ceferino Francisco Cantón', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Francisco Jose Joaquín Duran Verdú', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clara Roca-Quintana', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manuel Villanueva Pino', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Ignacio del Porras', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Hernando Teruel Elorza', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lilia del Río', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Encarnacion Obdulia Chamorro Mariño', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ale Luque Villanueva', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dolores Guerrero', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Remedios Bosch Patiño', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paca Cuadrado', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Norberto del Montero', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Domingo Villena Mendoza', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manuel del Estrada', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Efraín Marín Montesinos', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juan Pablo Morcillo Andrés', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emelina del Solís', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Reyes Sánchez Atienza', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmen Carbajo Acero', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maura Aguilar Oliva', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luisa Nuria Valls Pintor', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ana Garmendia Pino', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ignacio Tena Angulo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Apolonia Amaya Viña', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Régulo Márquez Mármol', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Flor Castells Pujol', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amaro Ramos Montaña', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leyre Tapia-Sanmiguel', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmelo Ramirez Carlos', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Consuela Albero-Peralta', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ofelia Pedraza', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Feliciana Arrieta', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yéssica del Llano', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vera Cabeza Burgos', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodora Oliver Ripoll', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leopoldo Belmonte Matas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Régulo Porcel Cornejo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Chucho Benjamín Villalonga Mateos', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosario Quiroga Roman', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cebrián del Blanch', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valerio del Múgica', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elodia Santamaria Malo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Armando Torre Larrañaga', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elvira Rovira-Briones', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maximiano de Querol', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Martirio Navarrete Barranco', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felipe Iborra Jódar', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nidia Puerta Otero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Silvio Juárez-Suarez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Pilar Neira Rivas', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Agapito Mesa Gras', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Blanca de Bustos', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guiomar Pedrero Padilla', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Encarnacion Pedrosa Aramburu', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Josué Morell Gelabert', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nazaret Catalá', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sabina Corominas Prat', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmelo Bruno Fajardo Conde', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heraclio Zamorano', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emigdio Sáez Real', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cebrián de Arnau', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rafa Edu Bas Albero', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Octavio Barco Galván', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Herberto de Lerma', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Zaida de Ramón', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cloe Dominguez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Francisco Javier Naranjo Rueda', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paulina Morata Mínguez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adora Vélez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carlota Castelló Priego', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Graciela Iriarte-Sevillano', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Hernán Reina Salcedo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Herminio Rius', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Luis Giménez Castilla', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ulises Belmonte Baños', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aníbal Espinosa Mesa', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cristian de Morante', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Olivia Benavente Izaguirre', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lidia Valdés-Caparrós', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Delia Menendez Villanueva', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Inés Galvez Valcárcel', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Francisca Acero Coca', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elisa Tamara Cadenas Girón', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Martín Mayoral Dueñas', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vidal Alejo Blanch Sarabia', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adrián Boix Albero', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lázaro Amo Palacios', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Abilio Carpio Peralta', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosenda de Zorrilla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nilda Guijarro Armengol', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eustaquio Trujillo Suárez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valero Rodríguez Palomino', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ariel Franco Villaverde', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodosio Carbajo Cabo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bienvenida Alsina Coronado', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Patricio Merino-Giner', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elisabet Cortina Bellido', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juan Luis Tudela Guijarro', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nando Priego Buendía', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ligia Navarrete Sevillano', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('René Armengol', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cruz Mármol Milla', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Josefa del Murillo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bárbara Naranjo-Gascón', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Inmaculada Paz Peláez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adelardo Ariza Pi', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lina Piñol-Villa', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Candelas de Gutiérrez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paulino Carrasco', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jordi Simó Lamas', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Hernando Rueda-Roma', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amalia Lamas', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marcos Rocha Saura', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Magdalena del Rosado', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jonatan Blanes Mesa', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fausto Marin Narváez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Esperanza Regina Farré Gordillo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Demetrio Canals Adadia', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Anita Ani Escamilla Ugarte', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paco Arteaga-Casas', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vasco Mayo Jordán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Julie Fortuny-Blazquez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Poncio Pineda Cabanillas', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cintia del Higueras', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ascensión Serra-Fábregas', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lino Belda', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marisa Riquelme Borrell', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sandalio Portillo Alvarez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Matías Bernat Alvarado', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paola Rincón Montalbán', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Arturo Porta', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Purificación Mur-Peña', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Luisa Mata-Pareja', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Roque Alemán Lara', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Beatriz Heredia Cabrera', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Melisa Sosa Téllez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sergio Higueras Machado', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yago del Pujol', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juan Carlos Raya Barón', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Buenaventura Aguado Espejo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Morena Sarabia', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Domitila Almeida Gomis', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ema Ibáñez Solé', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Daniela Rubio', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pánfilo Piñeiro-Mármol', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Poncio Guardiola Solano', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dionisio del Garcés', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Virgilio Ribera Quiroga', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marianela Ropero-Cobo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pánfilo Blanca Campoy', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leonel Farré-Barragán', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rocío Llano-Aliaga', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rodolfo Merino Royo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Abraham Maldonado-Guardia', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Miguel Ángel Serra Arias', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aura Losa Mármol', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('León Marciano Andrade Espinosa', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosaura Fernandez Castellanos', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Griselda Amelia Dávila Llobet', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Telmo Torres Roca', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Albert Lázaro Jerez Huguet', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Liliana Vila-Enríquez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmelita Sainz Noguera', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mar Magdalena Pardo Palomino', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bárbara Barroso Abad', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Soraya Amador Sacristán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vilma Rubio', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Daniela Morales Solís', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yolanda Mateo Báez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Georgina del Lastra', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nacio Zabala Portillo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ruth Isaura Muñoz Bernat', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elpidio Bermudez Torralba', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mar de Guijarro', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amelia de Avilés', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Haydée Quirós Zabala', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ezequiel Aliaga', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felicidad Toledo Gabaldón', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cristóbal Barrios Barberá', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Crescencia Cabrero Naranjo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Ignacio Iniesta Palomino', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Desiderio Soler Rovira', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nayara Nereida Salas Arteaga', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jacobo Batlle Morán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ricardo Escobar Donoso', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Roxana Gabaldón Bustos', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Natalio Humberto Gallo Amorós', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Albert Pacheco Sevilla', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fernando Alberdi', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Narciso Macias Barrio', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Epifanio Jover Benito', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Godofredo Reguera Valera', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Palmira Lobo-Calderon', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Encarnita Aguiló-Cruz', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cándida Roig', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ángeles Contreras Carrera', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Áurea Mateu Duarte', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Primitivo Quevedo Raya', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Roberto Sainz-Palmer', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Francisco Javier Pol Franco', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Octavia Adán Perales', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marc Hoz', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fortunata de Quero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heliodoro Valderrama', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Odalys Llorens Arjona', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Xavier Riba Cano', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Zaida Giralt Elías', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Otilia Andres Cózar', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Angelina Moraleda Giralt', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Plinio Alex Ros Jódar', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ana Sofía del Bosch', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodora Arias', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Araceli Quintana Santamaria', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Severo Palomo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Milagros Prado', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luciana Vidal Planas', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amaro del Macías', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eva Riba Piñeiro', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jenny Manzanares Soria', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Abraham Lledó', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clementina del Bas', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yaiza Tapia Alarcón', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Régulo de Diaz', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pili Luz Herranz Zamorano', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('José Manuel Nacho Soto Hervia', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('René Velasco', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Quirino del Garriga', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luz Patiño Merino', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Artemio Matas Juárez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Antonio Soler Rocha', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Margarita Vilar-Bellido', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Jesús Jurado Carrión', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Poncio Llopis Yuste', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Daniel Sancho Cazorla', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Glauco Solé', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Francisco Delgado Maldonado', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marc Lobato Pinedo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alejo Villalobos Pons', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cleto Naranjo Olmo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rita Montesinos Llano', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Etelvina Marín Molina', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adoración Adela Jara Domingo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rolando Pinto Echeverría', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manu Torrent Cardona', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eloy Cervantes', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lalo Castillo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Octavio Gimeno Pinto', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Samuel Salvador-Terrón', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juanita Campo Meléndez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Edgardo Arrieta Carnero', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amado Barón Sobrino', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Reyna Novoa', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maricela Morera Alcázar', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amanda Cerdán Tello', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Toribio Mancebo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Claudio Tolosa-Palomar', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Prudencia Zaida Torrijos Ribera', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ariel del Somoza', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eduardo Rebollo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maricela Gonzalo Seguí', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luis Ángel del Alfaro', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Herminio Guadalupe Núñez Miguel', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heraclio Garriga-Bayona', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Isidoro Morell Acero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Odalys de Barberá', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rubén Piñol-Saavedra', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Isabel de Carnero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Del Carmen Hilda Navarro Galvez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Geraldo Vilanova-Montoya', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paula Escribano', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dani Felix Gallo Tejero', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodora Tomas-Armengol', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leandra Osorio-Ibáñez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Iván Luciano Morante Álamo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lisandro Cerdán Iriarte', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elena Borja Benavides', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmina Gascón Jaén', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juan Carlos Buendía', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Joaquín Aragonés-Zapata', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmela Cid Sarmiento', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Osvaldo del Alonso', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Basilio Alemany-Lorenzo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ale Estévez Godoy', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Josué Tormo-Rey', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Miguela Canet', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maristela Iborra Crespi', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amílcar Samper Peláez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Héctor Cortina Franco', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teresita Álvaro Mendizábal', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ágata Alegria Valdés', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manuelita Mariscal Riquelme', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ema Rebeca Bermúdez Pont', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aurelio Alegre Bárcena', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eusebio Echeverría Asensio', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paloma Cobos', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Salvador Paz Mayol', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felicidad Pomares', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Angelina Gómez Benet', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eladio Cabello', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lorenza Quirós Manuel', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marcos Águila Antón', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nicolás Giner Valenciano', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clarisa Crescencia Lloret Pallarès', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alberto Palmer Diaz', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fernando Merino', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Delia Valentín', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eligia Morillo Iniesta', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Delfina Alexandra Segarra Muñoz', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Óscar Tormo Calvo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eva Peralta', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Verónica Robles-Neira', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lupita de Álvaro', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teo Pazos Guitart', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Máximo Losada Blanes', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Araceli Llorente Arnal', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sabas Barberá Ortega', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rómulo Rey Zaragoza', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Crescencia Blanes Alcántara', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Piedad Cuevas Zaragoza', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Salud Araujo Sanchez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jesusa Morcillo-Barreda', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cesar Juan Francisco Fabregat Hoyos', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Conrado Nuñez Solana', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cesar Peralta Requena', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luis Ángel Rivas Pedrosa', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María del Cabezas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosario Sastre Peiró', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bernarda Macias', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aránzazu Vigil Botella', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Baltasar Figueroa Escrivá', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Griselda Marín-Medina', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ana Figuerola Sastre', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bruno Vall Peinado', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cebrián Varela-Ballesteros', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Encarnacion Cortes Manzano', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Olalla del Crespo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ale Sandoval Diez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rolando Quevedo-Andrés', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Angelina Doménech Pou', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodoro Figuerola Ricart', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pedro Valero-Elías', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heraclio Vicente Vara Figuerola', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Joan Pastor Gallo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Arturo Perea Francisco', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gilberto Solera', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teófila Beltran Feliu', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gabriela Ródenas Hernández', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('José Ángel Cabañas Polo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Felicidad Isaura Vera Grau', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Flavia Gabaldón Bermúdez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Angelino Jimenez Franch', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Humberto Zamorano Ordóñez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ignacia Carmela Vives Daza', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Domingo Vega Tamayo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('León Guzman Gimeno', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pepita Sierra Hoz', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Calista Cid Mínguez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fabiola del Millán', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gema Castejón Sebastián', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manuel Arévalo Arenas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Virgilio de Agustín', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Corona Heredia Castrillo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Narcisa Feijoo-Luz', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amarilis del Ayllón', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Modesta del Reig', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rómulo Oliva Montero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leonardo Segarra', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amaro Diez Montero', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Tatiana Sevilla Cisneros', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eliana Paca Sacristán Contreras', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marcial Nicolás Machado', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Judith Molins', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Reyes Sandoval Duran', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sarita Campoy-Ramón', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pili Melisa Alonso Ferrándiz', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Duilio Segovia Vilar', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manu del Plana', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Griselda Bustamante', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dolores Pla Acevedo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Evangelina Mendez Oliver', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Inocencio Lladó Reguera', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Venceslás Rebollo Baquero', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Urbano del Martínez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heraclio Font Belda', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Melisa Lozano Gimeno', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lina Francisca Espejo Alegre', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ileana Borrell-Sanjuan', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lola de Rueda', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Julio César Agullo Madrid', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Prudencia Briones Hoyos', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dominga Cuervo Domingo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Corona Coca-Manso', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guiomar Salvador Corominas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Tecla Asensio Nadal', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Martin Andres', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Duilio Villegas Adán', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cayetano Agustín Torre', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Buenaventura Marti Martinez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lilia Burgos Olivera', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Antonia Ainara Mulet Marqués', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valeria Elías Escudero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Severo Samper-Camacho', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ema Cerro Matas', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eutropio Palomar Navarro', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Celso Céspedes Peña', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Hugo Mínguez Gallo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Miguel Galan-Cózar', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fausto del Asenjo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jovita Huertas Nevado', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Oriana Juan Mateo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Casemiro Bautista Rodríguez Alemany', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ariadna Bayo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dafne Cámara-Mur', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Flora Marina Abascal Ruano', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nicanor Cuéllar Sarmiento', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mohamed de Velázquez', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Flora Berrocal Lobato', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jordi Calvet Carmona', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luz del Cid', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ramona Velasco Zorrilla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fátima de Cases', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Herminio del Villena', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alexandra Carmina Riquelme Delgado', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guiomar Córdoba-Quiroga', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Camilo de Sarmiento', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alex de Aragón', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amarilis del Ferrer', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lorenza Gallart Capdevila', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cosme Diego Dominguez Bárcena', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosario Segura Mendoza', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ruben Barral Agullo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ana Belén Ileana Peral Santiago', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emelina Puga Donoso', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Baldomero Castilla Lucena', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Itziar Mateu Bejarano', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rafaela Peñas-Piquer', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nazaret Pozo-Cervantes', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Noa Madrigal Higueras', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Patricio Arce', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gastón Pinto Cordero', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Merche del Fabregat', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Íñigo Figueras Carreño', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marc Chaves-Checa', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manuel Guardiola Palacios', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jacinta del Sanmiguel', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Desiderio Gilberto Varela Albero', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Concepción Dueñas Quintero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alma de Cal', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manu Oller Bertrán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carina Valentina Valbuena Leon', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ximena Casado Rueda', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jacinto Valcárcel Diéguez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marcelino Marin-Alegria', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Raquel del Llano', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marciano Sanchez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrea Beltrán Losa', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosalva Olivera Ibañez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eufemia Juliana Cervantes Naranjo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Celestina Uría-Chamorro', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Custodio Pinedo Sastre', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dorita Alarcón Andres', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Domingo Morell Guerra', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ema Sáez Vall', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vicente del Guzmán', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cebrián Baños Pons', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pablo Anguita Chaves', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elvira Rivero Ferrán', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Artemio Cámara Carlos', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maxi Medina-Ortuño', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guiomar Doménech Luna', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Horacio Jódar Blazquez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bernardo Berto Doménech Pol', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luis Ángel Vinicio Bustamante Quintana', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosalva Amo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Román Vergara Alcolea', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emelina Uría Teruel', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yéssica Manzanares', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marisa Amaya Lozano Tovar', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adolfo del Arévalo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mónica Salgado Cortina', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sebastián Ricart Chacón', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Visitación Redondo Huguet', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Casandra Blanch Barrio', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marcelino Marco Grau', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rogelio Infante Fabra', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ascensión Nicolás Frías', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leocadio Almeida Luján', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fermín Pagès Buendía', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sandra Vera Hierro', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Olimpia Sola Alba', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gerónimo Gabino Hervia Asensio', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amelia Casares-Marcos', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Julia Paz Alba Meléndez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bautista Guzman Uribe', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Florina Celestina Miralles Riquelme', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jacobo Chico Calzada', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maxi Amigó-Téllez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ariel Castañeda Barceló', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrés Soria Quintana', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fermín Vendrell Fuente', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clementina Sabater-Salas', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clara Alcolea', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Áurea de Haro', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rufino Casas Aparicio', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Plácido Germán Guillen Barceló', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Margarita Gámez Vicente', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Estela Linares Palomino', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adán Saavedra Atienza', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nazaret Fábregas Castells', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pili Bustos-Caro', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elodia Cervera Lloret', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodosio Ojeda Pinto', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Estefanía Correa Díaz', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bibiana Rocha', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Arsenio de Suárez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Artemio Esparza-Amaya', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dalila Esteban Pereira', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Desiderio Rubio Ugarte', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adelia Camps-Godoy', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Geraldo Garzón Baeza', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amanda Hierro Jiménez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Flavio Mateos Girona', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Loreto Jimenez Salvà', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Florina Ribas Morán', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Baldomero Alemán Niño', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Catalina Hervás Caballero', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ignacio Alcaraz-Capdevila', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leoncio Melero-Gimeno', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nicanor Donaire Catalán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cebrián Canales Botella', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Yolanda Marqués-Viña', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adelina Cañete Grau', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Salomón Tolosa', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Pilar Roma Ibáñez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aitana Páez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maximiano Nebot Carlos', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gervasio Rueda', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Bautista Bernat Tirado', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Francisco Buendía Ramirez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aureliano del Vives', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Natividad Mateos Laguna', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alfonso Real Morcillo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eusebia Querol-Flores', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gabriel Céspedes Araujo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Horacio Viña Aguirre', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valerio Bárcena Torres', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eloísa Agustí Tamayo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alejandra Amo Pinedo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodoro del Álvarez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eloísa Carbó Galvez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Javi Navarro Diego', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Federico Soriano Ávila', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lisandro de Lucas', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jorge Amorós Armas', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Wálter Canet', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Azahara Luna Echeverría', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Agapito Ugarte Gargallo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guadalupe Herranz Alonso', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Desiderio del Tirado', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Loreto Esteban Morata', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nazario Narváez Balaguer', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rogelio Muñoz Alcázar', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luz del Varela', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrés Felipe Blasco Rojas', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elena Amaya', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alfonso del Amaya', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jose Manuel Redondo-Jove', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Piedad Lozano Royo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Graciela Redondo Valls', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fabricio Sánchez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carmelita Sonia Olmedo Gomis', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luis Amo Ocaña', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Patricia del Pons', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jacinta Torre Amor', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sebastián Robles Alvarez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luisina Pellicer-Medina', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Amador Mascaró Conesa', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sol Navarrete Fuente', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Luciano de Alberto', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rocío del Cobos', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jennifer del Zorrilla', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Casemiro Pujol', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Olga Adadia Gracia', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rogelio Vega Gomis', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pascuala Torrijos Carrión', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Viviana Lola Crespi Lamas', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eufemia Mancebo Rosado', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Begoña Sevilla Morán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paula Castañeda Coca', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heraclio Che Folch Frías', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paloma Cordero Arcos', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Piedad Albina Aguilera Plana', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jacinto de Anaya', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Flora Vila Vega', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Héctor Alarcón-Borrás', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Calista Ramos Torrent', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Benjamín Gallart Carreño', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aurelia Corominas', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dionisio Carmona Cantón', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vasco Boix Farré', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosalía Marcia Valcárcel Díez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ciro Figueroa-Alcázar', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Natividad Flores-Sevilla', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jessica Parra Aramburu', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Curro Tapia Cruz', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Liliana Amaya Alberola', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Arturo Prieto', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nieves Marco Higueras', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Salomé Grande Gabaldón', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosalía Portillo-Orozco', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Consuelo de Carrera', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Jesús Cortina-Mariscal', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jennifer Felisa Peláez Sanmiguel', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nilda Nebot Perez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Primitivo Corbacho Pi', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fidela Somoza Luz', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teodoro Palma Escamilla', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mireia Pilar Ballesteros Palma', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pepito Hoyos Almansa', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Remedios Catalán Roselló', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Elena Correa-Asensio', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Trinidad Luz Sánchez Tamayo', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Merche Querol-Codina', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Azahara Baeza Alberdi', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Néstor Fortuny Cazorla', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eligia Santamaria Coll', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valero Fito Nevado Galán', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Apolonia Arce Puente', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juanita del Fiol', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jorge Carro Juárez', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Delia Ricarda Rodriguez Pastor', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mónica Lloret-Arnau', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Juan Díez Barragán', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Darío del Torrecilla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ariel Mármol Folch', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Benito Tena Coll', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Remigio Arsenio Sanmiguel Cazorla', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Dorita Viana', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Celestina Beltrán-Arnaiz', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Emilio Prudencio Teruel Gutierrez', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cintia Sarita Patiño Pino', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Carmen Chacón', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Valentina Guerra-Roig', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Candelario Cayetano Llobet Pallarès', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gerónimo Rivero Caparrós', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Íñigo Parejo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Heraclio Jimenez Company', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paula Alvarez Juan', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rebeca Vera Donoso Garay', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pancho Barriga Expósito', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sonia Felipa Pozuelo Tomé', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Baldomero Gutierrez Báez', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rómulo Falcó', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adalberto Granados', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Adolfo Piquer Céspedes', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Irene Baños Pardo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Hernando Ramírez Ortega', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pacífica Rodríguez Peralta', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nélida Niño Casanova', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Manuelita Casado', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ignacia de Gámez', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Edmundo Llorens Farré', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Enrique Agustín Tapia', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Tere de Calleja', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Clemente Jordá Herrera', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Melisa Marco-Frías', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Nélida Calderón-Sanmartín', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sebastian Ribas Camps', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Américo Herranz Río', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eloísa del Tomas', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sigfrido Antúnez Guzmán', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Norberto de Solé', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rogelio Llorente Baena', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leoncio Bruno Bermudez Rosado', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sofía del Moya', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eligio de Losada', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Melchor Catalá Echeverría', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Edgardo Larrañaga Morcillo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ciriaco Balduino Niño Solís', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('José Hurtado Madrid', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Federico Montalbán Guardia', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pascual Tamarit Mosquera', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Jennifer de Ocaña', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Teo Marco Calderon', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('María Dolores Aguirre', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Javiera Huertas Domingo', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Édgar de Quintana', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Natanael Huertas Segovia', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Rosalía Urrutia Barros', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eva Calderon', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Agapito Sanz Abascal', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrés Felipe Cazorla', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Maristela Lola Alfaro Durán', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Vicenta Nuñez Barceló', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Raúl del Conde', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Eusebio Marqués Sacristán', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Francisco Javier Recio Barral', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Constanza Morales Verdejo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrés Felipe Bueno-Coello', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Fulgencio Cañete Aliaga', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ángeles Morales Cerdá', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Aroa Mendizábal Ariza', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Montserrat Torrecilla', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marisa Cadenas-Lozano', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marcela Criado-Calderón', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Pablo Marin Leiva', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Miguel Ángel Parejo Mulet', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Liliana Dávila Gonzalo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Gerónimo Amigó', 1);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Goyo Guerra Ureña', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Crescencia Abella Priego', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Serafina Pellicer', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Mireia Falcó Mayo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Miriam Anselma Montenegro Toledo', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Andrés Pla-Tamayo', 2);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Guadalupe Coello-Asenjo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ovidio Castejón-Pulido', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Marina Blanch Barriga', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Carlota Pedrosa-Daza', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Albano Sáenz', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Joaquina Luna Pereira Ojeda', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Ana Sofía Roura Ureña', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Sandra Josefina Quintanilla Chaparro', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Alexandra Porcel Lillo', 5);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Cristian Ambrosio Menéndez Mate', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Evelia Ámbar Feliu Huertas', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Lope Robles-Bartolomé', 3);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Paulino Salgado Lara', 4);
INSERT INTO animals.VISITANTES (Nombre, IdTipoVisitante) VALUES ('Leonel Montero Alberdi', 1);
