----REALIZA LAS SIGUIENTES QUERIES, DE LA BASE DE DATOS ZOOLOGICO

---1. INNER JOIN - Animales con Nombre de Su Cuidador y Hábitat
SELECT A.NOMBRE AS ANIMAL,
       C.NOMBRE AS CUIDADOR,
       H.NOMBRE AS HABITAT
FROM ANIMALES A
INNER JOIN CUIDADOR C ON A.IDCUIDADOR = C.ID
INNER JOIN HABITAT H ON A.IDHABITAT = H.ID;

--2. LEFT JOIN - Todos los Animales e Incluir los Sin Hábitat
SELECT A.NOMBRE AS ANIMAL,
       H.NOMBRE AS HABITAT
FROM ANIMALES A
LEFT JOIN HABITAT H ON A.IDHABITAT = H.ID;

--3. RIGHT JOIN - Todos los Cuidadores e Incluir Animales
SELECT C.NOMBRE AS CUIDADOR,
       A.NOMBRE AS ANIMAL
FROM CUIDADOR C
RIGHT JOIN ANIMALES A ON C.ID = A.IDCUIDADOR;

--4. FULL JOIN - Todas las Especialidades y Cuidadores

SELECT 
    E.Nombre AS Especialidad,
    C.Nombre AS Cuidador
FROM 
    Especialidad E
FULL JOIN 
    Cuidador C ON E.ID = C.IDEspecialidad;

--5. SELF JOIN - Pares de Animales con el Mismo Cuidador
SELECT A1.NOMBRE AS ANIMAL_1,
       A2.NOMBRE AS ANIMAL_2,
       C.NOMBRE AS CUIDADOR
FROM ANIMALES A1
JOIN ANIMALES A2 ON A1.IDCUIDADOR = A2.IDCUIDADOR AND A1.ID != A2.ID
JOIN CUIDADOR C ON A1.IDCUIDADOR=C.ID;