-- COUNT()
-- Contar el número de animales en cada hábitat.
SELECT H.NOMBRE AS HABITAT, 
       COUNT(A.ID) AS NUMERO_ANIMALES
FROM ANIMALES A
JOIN HABITAT H ON A.IDHABITAT = H.ID
GROUP BY H.NOMBRE;

-- SUM()
-- Calcular el salario total de los cuidadores 
-- contratados en el año 2022
SELECT SUM(SALARIO) AS SALARIO_TOTAL_2022
FROM CUIDADOR
WHERE EXTRACT(YEAR FROM FECHACONTRATACION) = 2022;

-- AVG()
-- Calcular la antigüedad promedio (en años) de los cuidadores.
SELECT AVG(EXTRACT(YEAR FROM AGE(C.FECHACONTRATACION))) AS ANTIGUEDAD,
       C.NOMBRE AS CUIDADOR
FROM CUIDADOR C
GROUP BY C.FECHACONTRATACION, C.NOMBRE;

-- MIN() && MAX()
-- Obtener el salario minimo y el salario maximo, 
-- para los cuidadores contratados en el 2023

SELECT MIN(C.SALARIO) SALARIO_MENOR_2023,
       MAX(C.SALARIO) SALARIO_MAYOR_2023
FROM CUIDADOR C
WHERE EXTRACT(YEAR FROM FECHACONTRATACION) = 2023;
