SELECT E.NOMBRE AS ESPECIE,
       EC.NOMBRE AS "ESTADO CONSERVACION",
       FA.NOMBRECOMUN AS FAMILIA
FROM ESPECIE E
INNER JOIN ESTADO_CONSERVACION EC ON E.IDESTADOCONSERVACION = EC.ID
JOIN FAMILIA FA ON E.IDFAMILIA = FA.ID
WHERE E.NOMBRE LIKE '%Delfín%';
