-- CREATE USER ADMIN ZOO
CREATE USER adminzoo WITH PASSWORD '******';
-- CREATE DB ZOOLOGICO
CREATE DATABASE zoologico WITH ENCODING 'UTF8' TEMPLATE template0 OWNER adminzoo;
-- GRANT ROLES TO USER ADMIN ZOO
GRANT ALL PRIVILEGES ON DATABASE zoologico TO adminzoo;
-- DELETE AND CREATE AGAIN ALL TABLES
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
--- SET CLIENT INSERT IN UTF8 METACHARSET
SET client_encoding = 'UTF8';
